# Copyright 2022 Guy’s and St Thomas’ NHS Foundation Trust
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: flip-app execution

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/answerdigital/nvflare-build-ci:2.2.5

    steps:
      - uses: actions/checkout@v3
      - name: Run NVFlare and Test
        run: |
          yes | cp ./app/flip-app ./ -r
          sed -i 's/download=True/download=False/' ./app/flip-app/custom/trainer.py
          sed -i 's/root="~\/data"/root="\/root\/data"/' ./app/flip-app/custom/trainer.py
          sed -i 's/root="~\/data"/root="\/root\/data"/' ./app/flip-app/custom/validator.py
          sed -i 's/self.local_train(fl_ctx, torch_weights, abort_signal)/# self.local_train(fl_ctx, torch_weights, abort_signal)/' ./app/flip-app/custom/trainer.py
          yes | cp ./utils/test.py ./
          python3 test.py
      - name: Archive Simulator Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: simulator-logs
          path: ./workspace-folder/simulate_job/log.txt